# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Code_Challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SDWebImage'

  # Pods for Code_Challenge

  target 'Code_ChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Code_ChallengeUITests' do
    # Pods for testing
  end

end
